### ISSUE TITLE
Removal of "pub mod primitive" broke SemVer

### ISSUE THREAD

**Issue by kvark** [nobuyuki83/del-msh#1]
The released version 0.1.19 is incompatible with 0.1.18

**Comment by nobuyuki83** [comment]
Thanks @kvark for pointing out this. I was not familiar with how the versioning should work. I will increment the major version when it loses backward compatibility from now on. 

BTW, the functions previously defined in `pub mod primitive ` are moved to `pub mod trimesh3_primitive`. 

Thanks!
